language: python
python: 
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6.6"
  - "3.6-dev"
  - "3.7-dev"

cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# run tests
script:
  - pytest