language: python
python: 
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# run tests
script: 
  - pytest --cov=./ 

# return coverage and let coveralls know the coverage percent
after_script:
  - coveralls